# -*- coding: utf-8 -*-
"""Copy of Tokenization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/182QdLg6R47XhDlpGaXnDDxom65Jxpqc3

Designed as a walkthrough with this [YouTube video](https://colab.research.google.com/drive/1y0KnCFZvGVf_odSfcNAws6kcDD7HsI0L?usp=sharing)

# Tokenization
"""

sample_text = "शेयर बाज़ार अनैलिसिस के तरीके 💹📈"

[ord(x)for x in "शेयर"]

chr(2351)

list("शेयर".encode("utf-8"))

singlechar = ord('न')
print(singlechar)
utf8enc = list('न'.encode("utf-8"))
print(utf8enc)
decoded_character = bytes(utf8enc).decode("utf-8")
print(decoded_character)

import regex as re
import unicodedata

def graphemes(text):
    return re.findall(r'\X', unicodedata.normalize("NFC", text))

print(graphemes("शेयर बाज़ार"))
print(graphemes("Share Market"))

import itertools

vowels = list("अआइईउऊएऐओऔऋॠऌॡ")
consonants = list("कखगघङचछजझञटठडढणतथदधनपफबभमयरलवशषसह")
matras = list("ािीुूेैोौृॄॅॉॢॣ")
extras = list("ंःँ")
virama = "्"

graphemesSet = set()

# Independent vowels
graphemesSet.update(vowels)

# Bare consonants
graphemesSet.update(consonants)

# Consonant + matra / nasal / visarga
for c in consonants:
    for m in matras:
        graphemesSet.add(c + m)
        for e in extras:
            graphemesSet.add(c + m + e)
    for e in extras:
        graphemesSet.add(c + e)

# Consonant conjuncts (C + Virama + C)
for c1, c2 in itertools.product(consonants, repeat=2):
    graphemesSet.add(c1 + virama + c2)
    for m in matras:
        graphemesSet.add(c1 + virama + c2 + m)
        for e in extras:
            graphemesSet.add(c1 + virama + c2 + m + e)

print(f"Total possible graphemes: {len(graphemesSet)}")

"""If we try to take all the combinations of graphemes it will exceed the total count of 5k tokens in vocabulary. Instead we will take unique individual graphemes in training dataset and use them as base tokens."""

# text from https://www.reedbeta.com/blog/programmers-intro-to-unicode/
trial = sample_text

rawTokens = graphemes(trial)

print('---')
print(trial)
print("length:", len(trial))
print('---')
print(rawTokens)
print("Raw tokens :", len(rawTokens))

def tokenToIdMap(token_to_id, rawTokens):
    return [token_to_id[tok] for tok in rawTokens]

def idToTokenMap(id_to_token, tokens):
    return [id_to_token[tok] for tok in tokens]

# Create set of unique tokens with their ids.
# Then generate new tokens with the mapping of raw tokens with token ids
rawTokens = graphemes(trial)
vocab = list(sorted(set(rawTokens)))
token_to_id = {tok: idx for idx, tok in enumerate(vocab)}
id_to_token = {idx: tok for tok, idx in token_to_id.items()}
tokens = tokenToIdMap(token_to_id,rawTokens)
print(token_to_id)
print(f"Vocab length: {len(vocab)}")

def get_stats(ids):
    counts = {}
    for pair in zip(ids, ids[1:]): # Pythonic way to iterate consecutive elements
        counts[pair] = counts.get(pair, 0) + 1
    return counts

stats = get_stats(tokens)
print(stats)
print(sorted(((v,k) for k,v in stats.items()), reverse=True))

top_pair = max(stats, key=stats.get)
top_pair

def merge(ids, pair, idx):
  # in the list of ints (ids), replace all consecutive occurences of pair with the new token idx
  newids = []
  i = 0
  while i < len(ids):
    # if we are not at the very last position AND the pair matches, replace it
    if i < len(ids) - 1 and ids[i] == pair[0] and ids[i+1] == pair[1]:
      newids.append(idx)
      i += 2
    else:
      newids.append(ids[i])
      i += 1
  return newids

print(merge([5, 6, 6, 7, 9, 1], (6, 7), 99))

tokens2 = merge(tokens, top_pair, 20)
print(tokens)
print("length:", len(tokens))
print(tokens2)
print("merged length:", len(tokens2))

def runMerges(num_merges = 5000, newTokens=[], startFromId=1):
    merges = {} # (str, str) -> str
    idx = startFromId
    for i in range(num_merges):
        stats = get_stats(newTokens)
        pair = max(stats, key=stats.get)
        # print(f"merging {pair} into a new token '{idx}'")
        newTokens = merge(newTokens, pair, idx)
        merges[pair] = idx
        idx += 1
    return (merges, newTokens)

newTokens = list(tokens) # copy so we don't destroy the original list
(trialmerges, newTokens)= runMerges(2, newTokens, len(vocab))
print(newTokens)
print(f"new token lengths: {len(newTokens)}")
print(trialmerges)

newVocab = {idx: vocab[idx] for idx in range(len(vocab))}
print(newVocab)
for (p0, p1), idx in trialmerges.items():
    print(f"{p0}, {p1}")
    newVocab[idx] = newVocab[p0] + newVocab[p1]

print(newVocab)

def decode(vocab, ids):
  # given ids (list of integers), return Python string
  return  "".join(vocab[idx] for idx in ids)

print(f"'{decode(newVocab, [17])}'")

def encode(merges, token_to_id, text):
  # given a string, return list of integers (the tokens)
  tokens = tokenToIdMap(token_to_id, graphemes(text))
  while len(tokens) >= 2:
    stats = get_stats(tokens)
    pair = min(stats, key=lambda p: merges.get(p, float("inf")))
    if pair not in merges:
      break # nothing else can be merged
    idx = merges[pair]
    tokens = merge(tokens, pair, idx)
  return tokens
print(f"original length: {len(graphemes(sample_text))}")
encodedToks = encode(trialmerges, token_to_id, sample_text)
print(encodedToks)
print(f"encoded length: {len(encodedToks)}")
print(f"decoded string '{decode(newVocab, encodedToks)}'")

text = """
मार्केट ट्रेंड्स (market trends) को समझना
मान लो कि आप एक नए शहर जैसे न्यूयॉर्क में बिना जीपीएस के गाड़ी चला रहे हो। आप देखते हो कि आपके आगे ज्यादातर कारें एक चौराहे पर बाईं ओर मुड़ रही हैं। आपको नहीं पता कि वे क्यों मुड़ रही हैं, लेकिन आप मान लेते हो कि उन्हें सबसे अच्छा रास्ता पता होगा। पैटर्न पर भरोसा करते हुए, आप भी उनके पीछे चलते हैं। इसी तरह, टेक्निकल एनालिसिस (Technical Analysis - TA) स्टॉक प्राइस के समय के साथ बनते पैटर्न्स को फॉलो करने के बारे में है। जैसे आप गाड़ियों को शहर में नेविगेट करने के लिए फॉलो करते हो, वैसे ही ट्रेडर्स मार्केट ट्रेंड्स (market trends) को फॉलो करते हैं ताकि समझ सकें कि स्टॉक प्राइस किस दिशा में जा रहे हैं।

इस लेख में, हम देखेंगे कि कैसे मार्केट ट्रेंड्स को समझने से ट्रेडर्स को सूचित निर्णय लेने में मदद मिलती है, जैसे कि आप एक अपरिचित जगह पर ट्रैफिक के फ्लो को फॉलो करते हो।

मार्केट ट्रेंड क्या है? (What is a Market Trend?)
एक मार्केट ट्रेंड (market trend) वह सामान्य दिशा होती है जिसमें एक स्टॉक या मार्केट एक निश्चित समयावधि में मूव करता है। यह ऊपर की ओर (upward - bullish), नीचे की ओर (downward - bearish), या साइडवेज़ (sideways - neutral) हो सकता है। इन ट्रेंड्स को पहचानना ऐसा है जैसे आप देख रहे हो कि ट्रैफिक किस दिशा में बह रहा है। जैसे गाड़ियों का फ्लो आपको एक नए शहर में दिशा देता है, वैसे ही स्टॉक की प्राइस में ट्रेंड आपको यह निर्णय लेने में मदद करता है कि खरीदना (buy), बेचना (sell), या रोकना (hold) है।

उदाहरण के लिए:

अपट्रेंड (बुलिश - Uptrend): प्राइस बढ़ रही हैं, और सामान्य मार्केट सेंटिमेंट पॉजिटिव है। इस स्थिति में, ट्रेडर्स खरीदारी के अवसरों की तलाश करते हैं।
डाउनट्रेंड (बेरिश - Downtrend): प्राइस लगातार गिर रही हैं, संकेत देते हैं कि विक्रेता हावी हैं। ट्रेडर्स बेचने की सोच सकते हैं या खरीदने से बच सकते हैं।
साइडवेज़ ट्रेंड (न्यूट्रल - Sideways Trend): प्राइस एक निश्चित रेंज में बिना स्पष्ट ऊपर या नीचे की दिशा के मूव करती हैं।

Image Courtesy: Tradingview

इन ट्रेंड्स को जल्दी पहचानने से ट्रेडर्स को संभावित प्रॉफिट अपॉर्चुनिटीज़ (profit opportunities) का फायदा उठाने का मौका मिलता है, जैसे कि आप एक अनजान शहर में सबसे भरोसेमंद रास्ता चुनते हैं। लेकिन आप इन ट्रेंड्स को कैसे पहचानते हैं? चलिए ट्रेंड्स के महत्व और इन्हें पहचानने के लिए इस्तेमाल किए जाने वाले टूल्स पर गौर करते हैं।

ट्रेडिंग में ट्रेंड्स का महत्व (The Importance of Trends in Trading)
मार्केट में ट्रेंड्स को पहचानना सूचित ट्रेडिंग निर्णय लेने के लिए महत्वपूर्ण है। जैसे ट्रैफिक के फ्लो को फॉलो करने से आप अपनी मंजिल तक सुरक्षित पहुंचते हैं, वैसे ही स्टॉक के प्राइस के फ्लो को फॉलो करने से आप बेहतर इन्वेस्टमेंट निर्णय ले सकते हैं। ज्यादातर ट्रेडर्स अपट्रेंड (uptrend) के दौरान खरीदना (buy) और डाउनट्रेंड (downtrend) के दौरान बेचना (sell) पसंद करते हैं। ऐसा करके, वे अपने ट्रेड्स को मार्केट की व्यापक दिशा के साथ संरेखित करते हैं, जिससे आवेगी निर्णय लेने का रिस्क (risk) कम होता है।

उदाहरण के लिए, जब भारतीय स्टॉक मार्केट अपट्रेंड (uptrend) में होता है, तो विभिन्न सेक्टर्स के कई स्टॉक्स सकारात्मक मार्केट सेंटिमेंट (market sentiment) के कारण बढ़ने लगते हैं। ट्रेडर्स जो इस ऊपर की गति को जल्दी पहचान लेते हैं, वे ट्रेंड से लाभ उठाने के लिए खुद को पोजीशन कर सकते हैं।

लेकिन आप वास्तव में इन ट्रेंड्स को कैसे पहचानते हैं? अगले सेक्शन में, हम मार्केट ट्रेंड्स को पहचानने के लिए उपयोग किए जाने वाले टूल्स और तरीकों का अन्वेषण करेंगे।

मार्केट ट्रेंड्स को कैसे पहचानें (How to Identify Market Trends)
मार्केट ट्रेंड्स को पहचानने के लिए कई टूल्स और तकनीकें हैं, जैसे आप एक नए शहर में अपना रास्ता खोजने के लिए संकेत और सिग्नल्स का उपयोग करते हैं।

1. प्राइस मूवमेंट्स (Price Movements)

ट्रेंड को पहचानने का सबसे सरल तरीका है समय के साथ प्राइस मूवमेंट्स (price movements) का अवलोकन करना। उच्च हायर्स (higher highs) और उच्च लोवर्स (higher lows) की एक श्रृंखला एक अपट्रेंड (uptrend) दर्शाती है, जबकि निम्न हायर्स (lower highs) और निम्न लोवर्स (lower lows) की एक श्रृंखला एक डाउनट्रेंड (downtrend) का संकेत देती है। एक साइडवेज ट्रेंड (sideways trend) में, प्राइस एक संकीर्ण सीमा के भीतर चलता है, सपोर्ट (support) और रेसिस्टेंस लेवल्स (resistance levels) के बीच बाउंस करता है।


2. ट्रेंडलाइन्स (trendlines)

ट्रेंडलाइन्स (trendlines) प्राइस चार्ट्स (price charts) पर खींची जाती हैं ताकि किसी स्टॉक की प्राइस मूवमेंट्स (price movements) के हाईज या लोज को जोड़ा जा सके। एक अपट्रेंड (uptrend) में, ट्रेंडलाइन (trendline) हायर लोज (higher lows) को जोड़ती है, जबकि एक डाउनट्रेंड (downtrend) में, यह लोअर हाईज (lower highs) को जोड़ती है। ये लाइन्स (lines) स्टॉक की मूवमेंट की दिशा की विजुअली (visually) पुष्टि करती हैं।


Image Courtesy: Tradingview

उदाहरण के लिए, अगर Infosys का स्टॉक लगातार ऊँचे निचले स्तर दिखा रहा है, तो इन पॉइंट्स को जोड़कर एक ट्रेंडलाइन ड्रॉ करने से अपट्रेंड (uptrend) की पुष्टि होगी।

3. मूविंग एवरेजेस (Moving Averages)

मूविंग एवरेजेस (moving averages) रोज़ाना की प्राइस फ्लक्चुएशंस (price fluctuations) को स्मूद बनाने में मदद करता है, जिससे ट्रेंड्स को देखना आसान हो जाता है। एक 50-डे मूविंग एवरेज (50-day moving average) पिछले 50 दिनों की औसत प्राइस को कैलकुलेट करता है। अगर स्टॉक प्राइस मूविंग एवरेज के ऊपर है, तो यह अपट्रेंड (uptrend) को दर्शाता है। अगर यह नीचे है, तो यह डाउनट्रेंड (downtrend) का संकेत हो सकता है।

मुनाफे वालेनुकसान वाले
एचबी स्टॉकहोल्डिंग्स लि.
98.82 (18.81%)
धारीवालकॉर्प लिमिटेड.
299.90 (17.87%)
Snehaa Organics Ltd.
91.90 (16.26%)
M & B Engineering Ltd.
502.75 (14.95%)
Image Courtesy: Tradingview

4. वॉल्यूम (Volume)

वॉल्यूम (volume) ट्रेंड्स (trends) की पहचान करने में महत्वपूर्ण होता है। हाई वॉल्यूम (high volume) किसी ट्रेंड (trend) की मजबूती की पुष्टि करता है, चाहे वह ऊपर की ओर हो या नीचे की ओर। उदाहरण के लिए, अगर कोई स्टॉक (stock) हाई ट्रेडिंग वॉल्यूम (high trading volume) के साथ बढ़ रहा है, तो यह एक मजबूत संकेत है कि अपट्रेंड (uptrend) संभावना है कि जारी रहेगा। इसके विपरीत, अगर कीमत बढ़ने के दौरान वॉल्यूम (volume) कम है, तो यह एक कमजोर या अस्थिर ट्रेंड (trend) का संकेत हो सकता है।


Image Courtesy: Tradingview

अब जब हमने ट्रेंड्स को पहचानने के लिए टूल्स का पता लगाया है, चलिए एक वास्तविक उदाहरण देखते हैं ताकि इन कॉन्सेप्ट्स को एक्शन में देख सकें।

मार्केट ट्रेंड का उदाहरण: टाटा मोटर्स (Tata Motors)

Image Courtesy: Tradingview

मान लीजिए Tata Motors का एक उदाहरण लेते हैं। पिछले महीने में, आपने देखा है कि इसके स्टॉक प्राइस ने लगातार हाईयर हाईज और हाईयर लोव्स बनाए हैं—यह एक स्पष्ट अपट्रेंड है। इसे जल्दी पहचानकर, आप शेयर खरीदने का फैसला करते हैं, उम्मीद करते हैं कि प्राइस बढ़ता रहेगा।

हालांकि, कुछ हफ्तों के बाद, स्टॉक प्राइस गिरने लगता है और आपके द्वारा पहले खींची गई ट्रेंडलाइन (trendline) के नीचे चला जाता है। यह संकेत दे सकता है कि अपट्रेंड खत्म हो गया है और स्टॉक डाउनट्रेंड (downtrend) में जा सकता है। इस संकेत पर कार्य करते हुए, आप प्राइस के और गिरने से पहले अपने प्रॉफिट लॉक करने के लिए शेयर बेच देते हैं।

यह उदाहरण दिखाता है कि ट्रेंड्स की पहचान कैसे आपके खरीद और बिक्री के निर्णयों का मार्गदर्शन कर सकती है, जैसे कि ट्रैफिक पैटर्न का अनुसरण आपको शहर में नेविगेट करने में मदद करता है। लेकिन मार्केट ट्रेंड्स में केवल सही समय पर खरीदने और बेचने से ज्यादा शामिल है—ट्रेंड्स क्यों बनते हैं, इसे समझना भी उतना ही महत्वपूर्ण है। आइए जानें कि मार्केट ट्रेंड्स को समझना क्यों महत्वपूर्ण है।

मार्केट ट्रेंड्स को समझना क्यों महत्वपूर्ण है (Why Understanding Market Trends is Crucial)
ट्रेंड्स की पहचान करना न केवल आपको बेहतर ट्रेडिंग निर्णय लेने में मदद करता है, बल्कि वोलेटाइल मार्केट कंडीशन्स के दौरान आपको शांत और केंद्रित भी रखता है। हर छोटे प्राइस मूवमेंट पर इमोशनल रिएक्ट करने के बजाय, आप बड़े चित्र—ट्रेंड पर निर्भर रहते हैं। यह कुछ ऐसा ही है जैसे किसी नए शहर में ट्रैफिक के फ्लो पर भरोसा करना बजाय हर सिग्नल पर निराश होने के।

ट्रेंड्स को समझकर, आप कर सकते हैं:

अपट्रेंड के दौरान खरीदें (Buy during an uptrend) ताकि बढ़ती कीमतों का लाभ उठा सकें।
डाउनट्रेंड के दौरान बेचें (Sell during a downtrend) ताकि और नुकसान से बच सकें।
साइडवेज़ ट्रेंड्स के दौरान होल्ड करें (Hold during sideways trends) जब तक मार्केट कोई स्पष्ट दिशा न दिखाए।
अब जब हमने समझ लिया है कि मार्केट ट्रेंड्स को समझना क्यों जरूरी है, तो आगे के चैप्टर्स की तैयारी में चलते हैं, जहां हम मार्केट मूवमेंट्स के पीछे के थ्योरीज़ में गहराई से जाएंगे।

निष्कर्ष और आगे की तैयारी (Conclusion and Looking Ahead)
मार्केट ट्रेंड्स को समझना टेक्निकल एनालिसिस में एक बुनियादी स्किल है। जैसे किसी नए शहर में ट्रैफिक के फ्लो का पालन करना आपको नेविगेट करने में मदद करता है, वैसे ही मार्केट ट्रेंड्स की पहचान करना आपको स्टॉक मार्केट में नेविगेट करने में मदद करता है। ट्रेंडलाइन्स (trendlines), मूविंग एवरिजेज (moving averages), और वॉल्यूम (volume) जैसे टूल्स का उपयोग करके, आप शुरुआती ट्रेंड्स की पहचान कर सकते हैं और सूचित ट्रेडिंग निर्णय ले सकते हैं।

अगले चैप्टर में, हम समझेंगे कि सपोर्ट और रेजिस्टेंस लेवल्स कैसे काम करते हैं।

बजाज ऑटो ने रिकॉर्ड मुनाफ़ा वृद्धि दर्ज की, राजस्व में 19% की वृद्धि; सोमवार को शेयर की कीमत पर रहेगी नज़र
लेखक: शराफ़त खान, ईटी ऑनलाइन • अपडेट किया गया: 7 नवंबर, 2025, शाम 7:34 बजे
पसंदीदा स्रोत बटन
वित्त वर्ष 26 की पहली तिमाही में कंपनी का कर-पश्चात लाभ क्रमिक आधार पर 4% घटकर ₹2,210 करोड़ रह गया। वित्त वर्ष 26 की अप्रैल-जून तिमाही में राजस्व तिमाही-दर-तिमाही 20% बढ़कर ₹13,133 करोड़ हो गया।
बजाज ऑटो लिमिटेड
बजाज ऑटो ने रिकॉर्ड मुनाफ़ा वृद्धि दर्ज की, राजस्व में 19% की वृद्धि; सोमवार को शेयर की कीमत पर रहेगी नज़र
प्रसिद्ध दोपहिया वाहन निर्माता कंपनी बजाज ऑटो लिमिटेड ने शुक्रवार को वित्त वर्ष 2026 की दूसरी तिमाही के लिए अपनी आय के आंकड़े जारी किए। कंपनी ने साल-दर-साल रिकॉर्ड मुनाफ़ा वृद्धि दर्ज की। तिमाही नतीजों से पहले, बजाज ऑटो के शेयर शुक्रवार को ₹8,717.00 पर स्थिर बंद हुए। कंपनी का बाजार पूंजीकरण ₹2.43 अरब है। सोमवार के बाजार में बजाज ऑटो के शेयरों में जोरदार उछाल आने की उम्मीद है।

कंपनी का वार्षिक लाभ 53% बढ़ा
बजाज ऑटो ने शुक्रवार को बताया कि दूसरी तिमाही में उसका समेकित शुद्ध लाभ 53% बढ़कर ₹2,122 करोड़ हो गया, जबकि पिछले साल इसी तिमाही में यह ₹1,385 करोड़ था। इस तिमाही में परिचालन से राजस्व ₹15,735 करोड़ रहा, जो पिछले वित्त वर्ष की इसी तिमाही के ₹13,247 करोड़ से 19% अधिक है। एक्सचेंज को दी गई जानकारी में, कंपनी ने बताया कि बेहतर वाहन मिश्रण और अब तक की सबसे अच्छी स्पेयर पार्ट्स बिक्री के कारण परिचालन राजस्व ₹15,000 करोड़ से अधिक रहा। कंपनी ने कहा कि उसके विभिन्न व्यवसायों में उसके मजबूत प्रदर्शन ने उसके पोर्टफोलियो के सबसे तेजी से बढ़ते सेगमेंट (इलेक्ट्रिक) को प्रभावित करने वाले व्यावसायिक व्यवधानों की भरपाई कर दी। वित्त वर्ष 26 की पहली तिमाही में कंपनी का कर-पश्चात लाभ क्रमिक आधार पर 4% घटकर ₹2,210 करोड़ रह गया। वित्त वर्ष 26 की अप्रैल-जून तिमाही में राजस्व तिमाही-दर-तिमाही 20% बढ़कर ₹13,133 करोड़ हो गया। बजाज ऑटो ने कहा कि EBITDA से पहले उसकी स्टैंडअलोन कमाई पहली बार ₹3,000 करोड़ के मील के पत्थर को पार कर गई, जिसमें मार्जिन 20.5% तक बढ़ गया। समीक्षाधीन तिमाही में इसके PAT ने भी ₹2,480 करोड़ का नया शिखर दर्ज किया, जबकि एक साल पहले की समान अवधि में यह ₹2,005 करोड़ था, जो 24% अधिक है। घरेलू मोटरसाइकिलों ने क्रमिक मात्रा-आधारित दोहरे अंकों की राजस्व वृद्धि देखी। बजाज ऑटो की घरेलू दोपहिया वाहनों की बिक्री 596,576 इकाई रही, जो एक साल पहले की समान अवधि में 636,801 इकाई से 6% कम है। वित्त वर्ष 26 की दूसरी तिमाही में वाणिज्यिक वाहनों की बिक्री 144,217 इकाई रही, जो पिछले वर्ष की इसी अवधि की 139,910 इकाई से 3% अधिक है। विभिन्न खंडों और 2W/3W में निर्यात राजस्व में साल-दर-साल 35% की वृद्धि हुई। कंपनी ने दूसरी तिमाही में 553,327 वाहनों का निर्यात किया, जो पिछले वर्ष की इसी अवधि की 444,793 इकाई की तुलना में 24% अधिक है। यह वृद्धि तिमाही-दर-तिमाही आधार पर 16% रही।
"""

# use the training set
#
ultraRawTokens = list(text.encode("utf-8"))
print(f"Ultra raw tokens: {len(ultraRawTokens)}")
rawTokens = graphemes(text)
vocab = sorted(set(rawTokens))
token_to_id = {tok: idx for idx, tok in enumerate(vocab)}
id_to_token = {idx: tok for tok, idx in token_to_id.items()}
tokens = tokenToIdMap(token_to_id,rawTokens)

print(f"Total tokens :{len(tokens)}")
print(f"rawTokes: {rawTokens[:10]}")
print(f"Vocab length: {len(vocab)}")
print(vocab)

newTokens = list(tokens) # copy so we don't destroy the original list
(merges, newTokens)= runMerges(2000, newTokens, len(vocab))
print(newTokens)
print(f"new token lengths: {len(newTokens)}")
print(f"merges count {len(merges)}")
print(sorted(merges.items(), key=lambda item: item[1], reverse=True)[:10])

newVocab = {idx: vocab[idx] for idx in range(len(vocab))}
for (p0, p1), idx in merges.items():
    # print(f"{p0}, {p1}")
    newVocab[idx] = newVocab[p0] + newVocab[p1]
# print(newVocab)
encodedStr = encode(merges, token_to_id, "इन ट्रेंड्स को जल्दी पहचानने से ट्रेडर्स")
print(encodedStr)
originalToks = {tok: decode(newVocab, [tok]) for tok in encodedStr}
print(originalToks)
print(decode(newVocab, encodedStr))

print(f"Ultra raw tokens: {len(ultraRawTokens)}")
print("tokens length:", len(tokens))

print("newTokens length:", len(newTokens))
print(f"compression ratio with respect to tokens: {len(tokens) / len(newTokens):.2f}X")
print(f"compression ratio with respect to Ultra raw tokens in bytes: {len(ultraRawTokens) / len(newTokens):.2f}X")